# Generated by Django 5.1.6 on 2025-03-02 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('fine_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_fines', to='loans.loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='fines',
            field=models.ManyToManyField(blank=True, related_name='loan_fines', to='loans.fine'),
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('repayment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_fine_payment', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayments', to='loans.loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='repayments',
            field=models.ManyToManyField(blank=True, related_name='loan_repayments', to='loans.repayment'),
        ),
    ]
