# Generated by Django 5.1.6 on 2025-03-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0004_nextofkin_district_nextofkin_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='members', to='accounts.account'),
        ),
    ]
